apiVersion: porter.sh/v1
kind: AgentConfig
metadata:
  name: default
  labels:
    porter.sh/generator: "porter-operator-bundle"
spec:
  # Values are set in helpers.sh based on the bundle parameters which are copied into agentconfig/*
  # where each file is a setting on the spec.