apiVersion: getporter.org/v1
kind: PorterConfig
metadata:
  name: default
  labels:
    getporter.org/generator: "porter-operator-bundle"
spec:
  # Values are supplied by the bundle parameter porter-config
  # If nothing is provided, defaults to the contents of defaults/porter-config-spec.yaml
