apiVersion: "kind.x-k8s.io/v1alpha4"
kind: "Cluster"
# Commenting out because I can't connect when we set this
networking:
  apiServerAddress: "{{.Address}}"
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://registry:5000"]
