apiVersion: porter.sh/v1
kind: Installation
metadata:
  name: hello-llama
  labels:
    porter.sh/testdata: "true"
spec:
  schemaVersion: 1.0.0
  targetNamespace: operator
  installationName: mellama
  bundle:
    repository: getporter/hello-llama
    version: 0.1.1
  parameters:
    name: "Porter Operator"
