
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: installations.porter.sh
spec:
  group: porter.sh
  names:
    kind: Installation
    listKind: InstallationList
    plural: installations
    singular: installation
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Installation is the Schema for the installations API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: InstallationSpec defines the desired state of Installation
            properties:
              action:
                description: Action defined in the bundle to execute. If unspecified,
                  Porter will run an install if the installation does not exist, or
                  an upgrade otherwise.
                type: string
              agentConfig:
                description: AgentConfig overrides the Porter Agent configuration
                  defined at the namespace or system level.
                properties:
                  installationServiceAccount:
                    description: InstallationServiceAccount specifies a service account
                      to run the Kubernetes pod/job for the installation image. The
                      default is to run without a service account. This can be useful
                      for a bundle which is targetting the kuernetes cluster that
                      the operator is installed in.
                    type: string
                  porterRepository:
                    description: PorterRepository is the repository for the Porter
                      Agent image. Defaults to ghcr.io/getporter/porter-agent
                    type: string
                  porterVersion:
                    description: PorterVersion is the tag for the Porter Agent image.
                      Defaults to latest.
                    type: string
                  pullPolicy:
                    description: PullPolicy specifies when to pull the Porter Agent
                      image. The default is to use PullAlways when the tag is canary
                      or latest, and PullIfNotPresent otherwise.
                    type: string
                  serviceAccount:
                    description: ServiceAccount is the service account to run the
                      Porter Agent under.
                    type: string
                  volumeSize:
                    anyOf:
                    - type: integer
                    - type: string
                    description: VolumeSize is the size of the persistent volume that
                      Porter will request when running the Porter Agent. It is used
                      to share data between the Porter Agent and the bundle invocation
                      image. It must be large enough to store any files used by the
                      bundle including credentials, parameters and outputs.
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                type: object
              credentialSets:
                description: CredentialSets is a list of credential set names.
                items:
                  type: string
                type: array
              parameterSets:
                description: ParameterSets is a list of parameter set names.
                items:
                  type: string
                type: array
              parameters:
                additionalProperties:
                  type: string
                description: Parameters is a list of parameter set names.
                type: object
              reference:
                description: Reference to the bundle in an OCI Registry, e.g. getporter/porter-hello:v0.1.1.
                type: string
            required:
            - action
            - reference
            type: object
          status:
            description: InstallationStatus defines the observed state of Installation
            properties:
              activeJob:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              lastJob:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
